Add list and form components
mgandore/to-do-ui pull request #3
Opened 2022-08-16 08:32 UTC by mgandore

-Reorganized html on task.component so that style is applied by
primeflex lib
-Added temporary task.service to mimic components interaction
-Reorganized style

2022-08-16 13:35 UTC, danielursu requested changes

2022-08-16 13:35 UTC, danielursu commented on to-do-ui/src/app/components/task-form/task-form.component.ts
> +	});
move to the property declaration

2022-08-16 13:35 UTC, danielursu commented on to-do-ui/src/app/components/task-form/task-form.component.ts
> +		public config: DynamicDialogConfig,
```suggestion
		private config: DynamicDialogConfig,
```
make private and declare a global property of actionType

2022-08-16 13:35 UTC, danielursu commented on to-do-ui/src/app/components/task-form/task-form.component.ts
> +		public config: DynamicDialogConfig,
this.actionType = this.config.data.actionType;

2022-08-16 13:35 UTC, danielursu commented on to-do-ui/src/app/components/task-form/task-form.component.ts
> +		}
switch

2022-08-16 13:35 UTC, danielursu commented on to-do-ui/src/app/components/task-form/task-form.component.ts
> +		if (actionType === "Add") {
verify with Enum

2022-08-16 13:35 UTC, danielursu commented on to-do-ui/src/app/components/task-form/task-form.component.ts
> +		} else {
verify also for Edit
now if I introduce actionType "adaugare" value it will invoke edit dialog :))

2022-08-16 13:35 UTC, danielursu commented on to-do-ui/src/app/components/task-form/task-form.component.ts
> +		this.messageService.add({ severity: "success", summary: "Success", detail: "Via MessageService", life: 500 });
add toast after the success/error return, not for clicking the button

2022-08-16 13:35 UTC, danielursu commented on to-do-ui/src/app/components/task-form/task-form.component.html
> +		[disabled]="this.taskForm.value['title'] === ''"></button>
```suggestion
		[disabled]="this.taskForm.value['title'] === ''"></button>
```

you can add a getter for this.taskForm.value['title']

2022-08-16 13:35 UTC, danielursu commented on to-do-ui/src/app/components/task-form/task-form.component.ts
> +	providers: [MessageService]
you should add MessageService on whole components.
in AppComponent HTML add <p-toast position="bottom-right"></p-toast> and fire toast whenever you want

2022-08-16 13:35 UTC, danielursu commented on to-do-ui/src/app/components/task-form/task-form.component.ts
> +			this.taskService.addTask(this.task);
did you try sending this.taskForm.value?

2022-08-16 13:35 UTC, danielursu commented on to-do-ui/src/app/components/task/task.component.ts
> +				actionType: "Edit"
enum

2022-08-16 13:35 UTC, danielursu commented on to-do-ui/src/app/components/task/task.component.ts
>  	public showButtons: boolean = false;
```suggestion
	public areButtonsRevealed: boolean = false;
```

2022-08-16 13:35 UTC, danielursu commented on to-do-ui/src/app/components/task-form/task-form.component.ts
> +	private createNewTaskDTO(data: Partial<any>): void { //QUESTION????
```suggestion
	private createNewTaskDTO(data: Partial<any>): void { //TODO: QUESTION????
```
for highlighting
question, please!

2022-08-16 13:54 UTC, mgandore commented on to-do-ui/src/app/components/task-form/task-form.component.ts
> +		} else {
😭

2022-08-16 15:24 UTC, mgandore commented on to-do-ui/src/app/components/task-form/task-form.component.ts
> +			this.taskService.addTask(this.task);
![image](https://user-images.githubusercontent.com/100152961/184916296-11e886dd-77d6-463e-b954-58a97820819a.png)
Only if I use that type as type of parameter in cause.

2022-08-17 08:55 UTC, danielursu requested changes

2022-08-17 08:55 UTC, danielursu commented on to-do-ui/src/app/components/task-form/task-form.component.ts
> +		return this.taskForm.value.title === "";
this will execute multiple times. Do you remember the solution of pure pipes?
Better approach is to have a getter for form title
`public get titleFormControl(): AbstractControl | null {
		return this.taskForm.get("title");
}`

2022-08-17 08:55 UTC, danielursu commented on to-do-ui/src/app/components/task-form/task-form.component.ts
> +		return this.taskForm.value.title === "";
in this way you will not have hardcoded "title" anywhere you need the title

2022-08-17 09:40 UTC, danielursu approved these changes

2022-08-17 11:25 UTC, merged